version: "3.9"
services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb@sha256:b569c23d6854564ec4d970bda86cddcf5b11c7c6362df62beb8ba8eafb8d54fd
    restart: always
    ports:
      - 2136:2136
      - 2135:2135
    hostname: localhost
    volumes:
    - ./ydb_certs:/ydb_certs
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
